### ISSUE TITLE
Compile cmake upon npm install for "zero"-dependency-style

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [unbornchikken/cmake-js#22] opened 2015-08-18 09:03 UTC
Hi,

have you considered, building `cmake` itself upon installation of this module? Something like...
```bash
git clone -b master --single-branch --depth 1 https://github.com/Kitware/CMake  node_modules/lib_cmake
./bootstrap --prefix=<this_modules_path>  # path to node_modules/lib_cmake 
make && make install
```
I currently like to integrate your module in [peterbraden/node-opencv](https://github.com/peterbraden/node-opencv). Since `opencv` and this module have a lot of dependencies itself, I care to reduce them by integrating the native dependencies like this. 

This would obviously support you argument about `cmake` being zero-dependent.

If it's worth a shot, I could send you a quick PR.

All the best!

**Comment by unbornchikken** [comment] 2015-08-18 09:29
The problem is that's a Linux only solution. It gotta be cross platform.

**Comment by eljefedelrodeodeljefe** [comment] 2015-08-18 17:31
I think the main issue would building, right? I've experienced this on another project. `Spawn` works differently for example.
```js
var spawn = require('child_process').spawn
spawn('cmd', ['/c', 'dir'], { stdio: 'inherit'})
```
Also you'd need doing this with MinGW installed or be in Cygwin (with other dependencies installed).

It would be ugly but I would do this.
* adding the git stuff to `npm install`
* Write some `install.js`, which is probably gonna end up ugly, but effective. This would compile conditional to the OS.
  * This could be done gracefully falling back to a system version of cmake
* Providing a flag / option for the user to either explicitly choose which one to use.

Maybe it's worth exploring it?

**Comment by unbornchikken** [comment] 2015-08-18 19:20
I'm of course not against any improvement. Lemme know, if ya have sumthin testable!

**Comment by unbornchikken** [comment] 2015-08-26 14:04
I'm closing this, but I'm still waiting for a PR to get landed. ;)

**Closed by unbornchikken** 2015-08-26 14:04 UTC
